default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

stages:
 - Test
 - Validate
 - Build
 - Deploy
 - Cleanup

cache:
  paths:
    - .terraform

before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  - export SSH_KEY_PAIR=${SSH_KEY_PAIR}
  - rm -rf .terraform
  - terraform --version
  - terraform init

terraform_init:
  stage: Test
  script:
    - terraform init

terraform_fmt:
  stage: Validate
  script:
    - terraform fmt 
  artifacts:
    paths:
      - .terraform/
      - .terraform.lock.hcl

terraform_plan:
  stage: Build
  script:
    - terraform plan -out="plan" -lock=false
  dependencies:
    - terraform_init
  artifacts:
    paths:
      - "plan"

terraform_apply:
  stage: Deploy 
  script:
    - terraform apply -input=false --auto-approve -var "ssh_key_pair=$SSH_KEY_PAIR" -lock=false
  dependencies:
    - terraform_plan

terraform_destroy:
  stage: Cleanup
  script:
    - terraform destroy -input=false --auto-approve -lock=false
  dependencies:
    - terraform_apply
  when: manual